### ISSUE TITLE
Last token compared to Google Authenticator App

### ISSUE THREAD

**Issue by pedromvieira** [maxneuvians/nio_google_authenticator#3]
Hi,

I just tested with current elixir release (1.5) and token generation and validation only pass with last displayed in Google Authenticator app.
Is there any other parameter to pass to sync them?

**Comment by maxneuvians** [comment]
I have not tested it in 1.5, but I will tomorrow. Is this just specific to 1.5 and it does work in 1.4? I also saw you posted the same question in yuce/pot. There is an options to specify an `interval_length` and a `window`. (https://github.com/yuce/pot/blob/master/src/pot.erl#L112) I did not expose those because most of the time all the items are in sync but I can try and take a look tomorrow.

**Comment by maxneuvians** [comment]
I just ran it on 1.5 and could not replicate the errors - make sure that your computers time is in sync. I will add in the config options in a little bit.

**Comment by maxneuvians** [comment]
Ok the latest version on hex now exposes:

`token_length` default `6`
`interval_length` default `30`
`window` default 0

**Comment by maxneuvians** [comment]
I am going to close for now, please re-open if you have any more issues.

**Comment by pedromvieira** [comment]
Thanks.
It was a non synced time on my mobile.
My Android was 15 seconds ahead due to GPS offset.
https://androidforums.com/threads/is-there-a-fix-for-the-15-second-time-offset.146893/

**Comment by pedromvieira** [comment]
Just to inform, I made a PR to POT that also works with nio_google_authenticator.

https://github.com/yuce/pot/pull/8

:pot.valid_totp(token, secret, [window: 1, addseconds: 30])

NioGoogleAuthenticator.validate_token(secret, token, [addseconds: 30, window: 1])
